# Generated by Django 4.2.6 on 2023-10-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=400)),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
