# Generated by Django 4.2.6 on 2023-12-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinghub', '0003_product_more_info_product_highlight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(default='', max_length=60)),
                ('address', models.GenericIPAddressField(default='')),
                ('phone', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=6000)),
            ],
        ),
    ]
