# Generated by Django 4.2.6 on 2023-12-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinghub', '0006_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
