# Generated by Django 4.2.6 on 2023-12-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinghub', '0007_orders_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_des', models.CharField(max_length=4000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
